excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ramakrishna-git.github.io
title: ramakrishna-git
tagline: A log of everyday life
description: My awesome new site
paginate: 5